/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { AIEnrichmentFieldResultField } from './aIEnrichmentFieldResultField';

/**
 * Before/after comparison for a single enriched field.
 */
export interface AIEnrichmentFieldResult {
  /** The field that was enriched. */
  field: AIEnrichmentFieldResultField;
  /** Value before enrichment. */
  original?: string | null;
  /** Value after enrichment. */
  enriched?: string | null;
  /** True when the enriched value differs from the original. */
  changed?: boolean;
}
