/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

export type AIListingEnrichmentRequestFieldsItem =
  (typeof AIListingEnrichmentRequestFieldsItem)[keyof typeof AIListingEnrichmentRequestFieldsItem];

export const AIListingEnrichmentRequestFieldsItem = {
  title: 'title',
  description: 'description',
  meta_description: 'meta_description',
} as const;
