/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { AIListingEnrichmentRequestFieldsItem } from './aIListingEnrichmentRequestFieldsItem';

/**
 * AI enrichment request targeting an existing listing by ID.
 */
export interface AIListingEnrichmentRequest {
  /** ID of the listing to enrich. */
  listing_id: string;
  /** Listing fields to enrich. If empty, all fields are enriched. */
  fields?: AIListingEnrichmentRequestFieldsItem[];
  /** Custom SEO keywords. If empty, keywords are inferred from the listing. */
  keywords?: string[];
  /** When True, persists AI results to the database; otherwise returns a preview. */
  apply?: boolean;
  /** When True, regenerates output even if target fields already have values. */
  force?: boolean;
}
