/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { AIListingEnrichmentRequestEnrichedValues } from './aIListingEnrichmentRequestEnrichedValues';
import type { AIListingEnrichmentRequestFieldsItem } from './aIListingEnrichmentRequestFieldsItem';

/**
 * AI enrichment request targeting an existing listing by ID.
 */
export interface AIListingEnrichmentRequest {
  /** ID of the listing to enrich. */
  listing_id: string;
  /** Listing fields to enrich. If empty, all fields are enriched. */
  fields?: AIListingEnrichmentRequestFieldsItem[];
  /** Custom SEO keywords. If empty, keywords are inferred from the listing. */
  keywords?: string[];
  /** When True, persists enriched_values to the database. AI is never called in this mode — enriched_values must be supplied. */
  apply?: boolean;
  /** Only meaningful when apply=False. When True, calls the AI even if target fields already have enriched values. */
  force?: boolean;
  /** Pre-computed enriched values to persist. Required when apply=True. Keys must be valid AIEnrichmentTargetField names. */
  enriched_values?: AIListingEnrichmentRequestEnrichedValues;
}
