/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Pre-computed enriched values to persist. Required when apply=True. Keys must be valid AIEnrichmentTargetField names.
 */
export type AIListingEnrichmentRequestEnrichedValues = { [key: string]: string } | null;
