/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { AIEnrichmentFieldResult } from './aIEnrichmentFieldResult';

/**
 * Response for the listing AI enrichment endpoint.
 */
export interface AIListingEnrichmentResponse {
  listing_id: string;
  /** True when results were persisted to the database. */
  applied?: boolean;
  /** Identifier of the AI model used. */
  model_used: string;
  /** Keywords that guided the enrichment. */
  keywords_used?: string[];
  /** Per-field before/after results. */
  results?: AIEnrichmentFieldResult[];
}
