/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { AITextOptimizationRequestFieldsItem } from './aITextOptimizationRequestFieldsItem';

/**
 * Optimize free text using AI with optional SEO keyword guidance.
 */
export interface AITextOptimizationRequest {
  /**
   * Original text content to optimize.
   * @minLength 5
   */
  content: string;
  /** SEO keywords; the first entry is treated as the primary keyword. */
  keywords?: string[];
  /** Output fields to generate. Defaults to all three. */
  fields?: AITextOptimizationRequestFieldsItem[];
}
