/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { AIEnrichmentOutput } from './aIEnrichmentOutput';

/**
 * Response for the free-text AI optimisation endpoint.
 */
export interface AITextOptimizationResponse {
  /** Identifier of the AI model used (e.g. 'gpt-4o'). */
  model_used: string;
  /** Keywords that guided the optimisation. */
  keywords_used?: string[];
  output: AIEnrichmentOutput;
}
