/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorDetail } from './errorDetail';
import type { Meta } from './meta';
import type { SiteConfigSuggestResponse } from './siteConfigSuggestResponse';

export interface ApiResponseSiteConfigSuggestResponse {
  /** Whether the request succeeded. */
  success: boolean;
  /** Response payload; present when success=True. */
  data?: SiteConfigSuggestResponse | null;
  /** Pagination metadata for list responses. */
  meta?: Meta | null;
  /** Optional human-readable message. */
  message?: string | null;
  /** Error details; present when success=False. */
  errors?: ErrorDetail[] | null;
  /** Correlation ID for distributed tracing. */
  trace_id?: string | null;
}
