/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorDetail } from './errorDetail';
import type { ListingDetailRead } from './listingDetailRead';
import type { Meta } from './meta';

export interface ApiResponseListingDetailRead {
  /** Whether the request succeeded. */
  success: boolean;
  /** Response payload; present when success=True. */
  data?: ListingDetailRead | null;
  /** Pagination metadata for list responses. */
  meta?: Meta | null;
  /** Optional human-readable message. */
  message?: string;
  /** Error details; present when success=False. */
  errors?: ErrorDetail[];
  /** Correlation ID for distributed tracing. */
  trace_id?: string;
}
