/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { BulkEnrichmentItemResult } from './bulkEnrichmentItemResult';

/**
 * Aggregated result of a bulk enrichment operation.
 */
export interface BulkEnrichmentResponse {
  /** @minimum 0 */
  total_requested: number;
  /** @minimum 0 */
  enriched: number;
  /** @minimum 0 */
  skipped: number;
  /** @minimum 0 */
  failed: number;
  results?: BulkEnrichmentItemResult[];
}
