/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Returned immediately when a background bulk job is accepted (HTTP 202).
 */
export interface BulkJobAccepted {
  job_id: string;
  job_type: string;
  status?: string;
  /**
   * Number of items to process.
   * @minimum 0
   */
  total: number;
  message: string;
}
