/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { BulkEnrichmentItemResultFieldsChangedItem } from './bulkEnrichmentItemResultFieldsChangedItem';

/**
 * Per-listing result within a bulk enrichment response.
 */
export interface BulkEnrichmentItemResult {
  listing_id: string;
  /** 'enriched', 'skipped', or 'error' */
  status: string;
  fields_changed?: BulkEnrichmentItemResultFieldsChangedItem[];
  /** Error message when status is 'error'. */
  error?: string | null;
}
