/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { BulkEnrichmentRequestLocalesItem } from './bulkEnrichmentRequestLocalesItem';

/**
 * Request to enrich multiple listings in one bulk call.
 */
export interface BulkEnrichmentRequest {
  /** Explicit list of listing IDs to enrich. If empty, enrich all unenriched listings. */
  listing_ids?: string[];
  /** Target locales to generate. Defaults to all supported locales. */
  locales?: BulkEnrichmentRequestLocalesItem[];
  /** Shared SEO keywords. If empty, keywords are inferred per listing. */
  keywords?: string[];
  /** When True, regenerates locales even if they already have stored translations. */
  force?: boolean;
  /** When set (and listing_ids is empty), restricts bulk enrichment to this partner. */
  source_partner?: string | null;
  /**
   * Maximum number of listings to process in this call.
   * @minimum 1
   * @maximum 200
   */
  limit?: number;
}
