/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

export type BulkEnrichmentRequestFieldsItem =
  (typeof BulkEnrichmentRequestFieldsItem)[keyof typeof BulkEnrichmentRequestFieldsItem];

export const BulkEnrichmentRequestFieldsItem = {
  title: 'title',
  description: 'description',
  meta_description: 'meta_description',
} as const;
