/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Current state of a background bulk job — returned by polling / SSE.
 */
export interface BulkJobStatus {
  job_id: string;
  job_type: string;
  /** running | completed | failed */
  status: string;
  total: number;
  done: number;
  failed: number;
  skipped: number;
  progress_pct: number;
  errors?: string[];
  created_at: string;
  finished_at?: string | null;
}
