/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { BulkEnrichmentRequestFieldsItem } from './bulkEnrichmentRequestFieldsItem';

/**
 * Request to enrich multiple listings in one call.
 */
export interface BulkEnrichmentRequest {
  /** Explicit list of listing IDs to enrich. If empty, enrich all unenriched listings. */
  listing_ids?: string[];
  /** Fields to enrich. Defaults to all three. */
  fields?: BulkEnrichmentRequestFieldsItem[];
  /** Shared SEO keywords. If empty, keywords are inferred per listing. */
  keywords?: string[];
  /** When True, regenerates output even if target fields already have values. */
  force?: boolean;
  /** When set (and listing_ids is empty), restricts bulk enrichment to this partner. */
  source_partner?: string | null;
  /**
   * Maximum number of listings to process in this call.
   * @minimum 1
   * @maximum 200
   */
  limit?: number;
}
