/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { BulkEnrichmentItemResultLocalesGeneratedItem } from './bulkEnrichmentItemResultLocalesGeneratedItem';

/**
 * Per-listing result within a bulk enrichment response.
 */
export interface BulkEnrichmentItemResult {
  listing_id: string;
  /** 'enriched', 'skipped', or 'error' */
  status: string;
  locales_generated?: BulkEnrichmentItemResultLocalesGeneratedItem[];
  /** Error message when status is 'error'. */
  error?: string | null;
}
