/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Metadata about the last confidence score calculation.
 */
export interface ConfidenceMeta {
  job_id: string;
  /**
   * Number of listings used to calculate scores.
   * @minimum 0
   */
  sample_count: number;
  /** ISO 8601 timestamp of the last calculation. */
  updated_at: string;
}
