/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { DuplicateEntry } from './duplicateEntry';

/**
 * Response body for GET /duplicates.
 */
export interface DuplicatesResponse {
  duplicates?: DuplicateEntry[];
  /**
   * Total number of URL groups with duplicates.
   * @minimum 0
   */
  total?: number;
}
