/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * A group of listings sharing the same source_url.
 */
export interface DuplicateEntry {
  source_url: string;
  /**
   * Number of listings with this URL.
   * @minimum 2
   */
  count: number;
}
