/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Enrichment counts for a single source partner.
 */
export interface EnrichmentSourceStats {
  /**
   * Total listings from this source.
   * @minimum 0
   */
  total: number;
  /**
   * Listings with at least one AI-enriched field.
   * @minimum 0
   */
  enriched_count: number;
}
