/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { EnrichmentStatsBySource } from './enrichmentStatsBySource';

/**
 * Aggregated enrichment statistics across all listings.
 */
export interface EnrichmentStats {
  /** @minimum 0 */
  total_listings: number;
  /** @minimum 0 */
  enriched_count: number;
  /** @minimum 0 */
  not_enriched_count: number;
  /**
   * Percentage of listings enriched.
   * @minimum 0
   * @maximum 100
   */
  enrichment_percentage: number;
  /** Per-source breakdown keyed by source partner slug. */
  by_source?: EnrichmentStatsBySource;
}
