/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

export type EnrichmentStatsParams = {
  /**
   * Filter stats by source partner
   */
  source_partner?: string | null;
};
