/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { EnrichmentSourceStats } from './enrichmentSourceStats';

/**
 * Per-source breakdown keyed by source partner slug.
 */
export type EnrichmentStatsBySource = { [key: string]: EnrichmentSourceStats };
