/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Preview of AI enrichment for a listing (all three SEO fields).
 */
export interface EnrichmentPreview {
  /** Title before enrichment. */
  original_title?: string | null;
  /** Title after enrichment. */
  enriched_title?: string | null;
  /** Description before enrichment. */
  original_description?: string | null;
  /** Description after enrichment. */
  enriched_description?: string | null;
  /** Meta description before enrichment. */
  original_meta_description?: string | null;
  /** Meta description after enrichment. */
  enriched_meta_description?: string | null;
  /** Identifier of the AI model used. */
  model_used: string;
}
