/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Preview of AI enrichment for a single listing (description only).
 */
export interface EnrichmentPreview {
  /** Description before enrichment. */
  original_description?: string | null;
  /** Description after enrichment. */
  enriched_description?: string | null;
  /** Identifier of the AI model used. */
  model_used: string;
}
