/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Structured error detail for client consumption.
 */
export interface ErrorDetail {
  /** Machine-readable error code (e.g. 'NOT_FOUND', 'VALIDATION_ERROR'). */
  code: string;
  /** Human-readable error description. */
  message: string;
  /** Name of the field that caused the error, if applicable. */
  field?: string | null;
}
