/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

export type ExportExcelParams = {
  district?: string | null;
  county?: string | null;
  parish?: string | null;
  property_type?: string | null;
  typology?: string | null;
  business_type?: string | null;
  source_partner?: string | null;
  scrape_job_id?: string | null;
  price_min?: number | string | null;
  price_max?: number | string | null;
  area_min?: number | null;
  area_max?: number | null;
  bedrooms_min?: number | null;
  bedrooms_max?: number | null;
  bathrooms_min?: number | null;
  bathrooms_max?: number | null;
  energy_certificate?: string | null;
  has_garage?: boolean | null;
  has_pool?: boolean | null;
  has_elevator?: boolean | null;
  has_balcony?: boolean | null;
  has_air_conditioning?: boolean | null;
  created_after?: string | null;
  created_before?: string | null;
  search?: string | null;
};
