/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

export type ExportJsonParams = {
  district?: string | null;
  county?: string | null;
  property_type?: string | null;
  source_partner?: string | null;
  scrape_job_id?: string | null;
  price_min?: number | string | null;
  price_max?: number | string | null;
};
