/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

export type ImodigiSearchLocationsParams = {
  /**
   * country | region | district | county | parish
   */
  level: string;
  country_id?: number | null;
  region_id?: number | null;
  district_id?: number | null;
  county_id?: number | null;
  q?: string | null;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
};
