/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Allowed values returned by GET /crm-property-values.php.
 */
export interface ImodigiCatalogValues {
  property_type?: string[];
  business_type?: string[];
  state?: string[];
  availability?: string[];
  energy_class?: string[];
  country?: string[];
}
