/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Request body for POST /api/v1/imodigi/publications/reset.
 */
export interface ImodigiResetRequest {
  /** Listing IDs whose export records should be deleted. Pass an empty list to reset ALL export records. */
  listing_ids?: string[];
}
