/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Item de uma das categorias do sync report.
 */
export interface ImodigiSyncItem {
  /** ID local do listing */
  listing_id?: string | null;
  /** property_id no Imodigi */
  imodigi_property_id?: number | null;
  /** property_id guardado na nossa DB */
  local_property_id?: number | null;
  /** Referência externa / partner_id comum aos dois lados */
  partner_id?: string | null;
  /** Status do registo em imodigi_exports (se existir) */
  export_status?: string | null;
  /** only_in_crm | only_in_db | in_both | never_exported */
  divergence: string;
}
