/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Request body for POST /api/v1/imodigi/publish/bulk.
 */
export interface ImodigiBulkExportRequest {
  /** Explicit listing IDs to export. When empty all listings not yet published (or failed) are exported. */
  listing_ids?: string[];
  /** Imodigi store ID. Overrides the IMODIGI_CLIENT_ID setting when provided. */
  client_id?: number | null;
  /** Only export listings from this source partner. */
  source_partner?: string | null;
  /** Only export listings that are enriched (true) or not enriched (false). */
  is_enriched?: boolean | null;
  /**
   * Maximum number of listings to process when listing_ids is empty.
   * @minimum 1
   * @maximum 500
   */
  limit?: number;
}
