/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

export interface ImodigiLocationItem {
  id: number;
  name: string;
  id_pais?: number | null;
  id_regiao?: number | null;
  id_distrito?: number | null;
  id_concelho?: number | null;
}
