/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Contagens do sync report.
 */
export interface ImodigiSyncSummary {
  /** Total de propriedades no Imodigi CRM */
  total_in_crm: number;
  /** Total de registos published/updated/failed/pending na nossa DB */
  total_in_db: number;
  /** Sincronizados — existem nos dois lados */
  total_in_both: number;
  /** Existem no CRM mas sem registo local */
  total_only_in_crm: number;
  /** Exportados mas já não existem no CRM */
  total_only_in_db: number;
  /** Listings locais que nunca foram exportados */
  total_never_exported: number;
  /** Em ambos os lados mas property_id diverge */
  total_property_id_mismatches: number;
}
