/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Returned after a successful export to Imodigi.
 */
export interface ImodigiExportResponse {
  listing_id: string;
  imodigi_property_id?: number | null;
  imodigi_reference?: string | null;
  status: string;
  /** 'created' or 'updated' */
  action: string;
}
