/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { ImodigiSyncItem } from './imodigiSyncItem';
import type { ImodigiSyncSummary } from './imodigiSyncSummary';

/**
 * Resultado completo do sync check entre a DB local e o Imodigi CRM.
 */
export interface ImodigiSyncReport {
  client_id: number;
  checked_at: string;
  summary: ImodigiSyncSummary;
  /** partner_id existe nos dois lados — sincronizados */
  in_both?: ImodigiSyncItem[];
  /** Temos export record published/updated mas o partner_id já não existe no CRM */
  only_in_db?: ImodigiSyncItem[];
  /** Existem no CRM mas sem export record correspondente na DB */
  only_in_crm?: ImodigiSyncItem[];
  /** Listings locais com partner_id que nunca foram exportados para o Imodigi */
  never_exported?: ImodigiSyncItem[];
  /** partner_id bate nos dois lados mas o property_id diverge (re-criação no CRM) */
  property_id_mismatches?: ImodigiSyncItem[];
}
