/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

export interface ImodigiExportRead {
  id: string;
  listing_id: string;
  imodigi_property_id?: number | null;
  imodigi_reference?: string | null;
  imodigi_client_id?: number | null;
  status: string;
  last_error?: string | null;
  last_exported_at?: string | null;
  created_at: string;
  updated_at: string;
}
