/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Request body for POST /api/v1/imodigi/export/{listing_id}.
 */
export interface ImodigiExportRequest {
  /** Imodigi store ID. Overrides the IMODIGI_CLIENT_ID setting when provided. */
  client_id?: number | null;
}
