/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { JobConfig } from './jobConfig';

/**
 * Schema for creating a new scrape job.
 */
export interface JobCreate {
  /**
   * Site configuration key (e.g. 'pearls').
   * @minLength 1
   */
  site_key: string;
  /** URL to begin scraping from. */
  start_url: string;
  /**
   * Maximum number of listing pages to scrape.
   * @minimum 1
   * @maximum 500
   */
  max_pages?: number;
  /** Optional runtime configuration overrides. */
  config?: JobConfig | null;
}
