/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Runtime configuration for a scrape job.
 */
export interface JobConfig {
  /**
   * Minimum delay between requests (seconds).
   * @minimum 0.5
   */
  min_delay?: number;
  /**
   * Maximum delay between requests (seconds).
   * @minimum 1
   */
  max_delay?: number;
  /** Custom User-Agent string. Should include bot name and a contact URL or email. */
  user_agent?: string | null;
}
