/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { JobListReadStatus } from './jobListReadStatus';
import type { JobProgress } from './jobProgress';

/**
 * Compact scrape job schema for paginated list views.
 */
export interface JobListRead {
  id: string;
  site_key: string;
  status: JobListReadStatus;
  progress?: JobProgress | null;
  started_at?: string | null;
  last_heartbeat_at?: string | null;
  cancel_requested_at?: string | null;
  completed_at?: string | null;
  created_at: string;
  updated_at?: string | null;
}
