/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { JobLogEntryLevel } from './jobLogEntryLevel';

/**
 * A single structured log entry emitted during a scrape job.
 */
export interface JobLogEntry {
  /** Log severity level. */
  level: JobLogEntryLevel;
  /** Human-readable log message. */
  message: string;
  /** URL associated with this log entry, if applicable. */
  url?: string | null;
  /** ISO-8601 timestamp of the log entry. */
  timestamp?: string | null;
}
