/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Log severity level.
 */
export type JobLogEntryLevel = (typeof JobLogEntryLevel)[keyof typeof JobLogEntryLevel];

export const JobLogEntryLevel = {
  info: 'info',
  warning: 'warning',
  error: 'error',
} as const;
