/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Real-time progress counters for a running job.
 */
export interface JobProgress {
  /**
   * Number of pages fetched so far.
   * @minimum 0
   */
  pages_visited?: number;
  /**
   * Number of listing URLs discovered.
   * @minimum 0
   */
  listings_found?: number;
  /**
   * Number of listings successfully scraped.
   * @minimum 0
   */
  listings_scraped?: number;
  /**
   * Number of errors encountered.
   * @minimum 0
   */
  errors?: number;
}
