/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { JobConfig } from './jobConfig';
import type { JobProgress } from './jobProgress';
import type { JobReadLogs } from './jobReadLogs';
import type { JobReadStatus } from './jobReadStatus';
import type { JobReadUrls } from './jobReadUrls';

/**
 * Full scrape job detail response.
 */
export interface JobRead {
  id: string;
  site_key: string;
  base_url?: string | null;
  start_url: string;
  max_pages: number;
  status: JobReadStatus;
  progress?: JobProgress | null;
  config?: JobConfig | null;
  /** Structured log entries keyed by step or timestamp. */
  logs?: JobReadLogs;
  /** Discovered and visited URL sets. */
  urls?: JobReadUrls;
  /** Terminal error message when status='failed'. */
  error_message?: string | null;
  started_at?: string | null;
  last_heartbeat_at?: string | null;
  cancel_requested_at?: string | null;
  completed_at?: string | null;
  created_at: string;
  updated_at?: string | null;
}
