/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { JobConfig } from './jobConfig';
import type { JobLogEntry } from './jobLogEntry';
import type { JobProgress } from './jobProgress';
import type { JobReadStatus } from './jobReadStatus';
import type { JobUrlState } from './jobUrlState';

/**
 * Full scrape job detail response.
 */
export interface JobRead {
  id: string;
  site_key: string;
  base_url?: string | null;
  start_url: string;
  max_pages: number;
  status: JobReadStatus;
  progress?: JobProgress | null;
  config?: JobConfig | null;
  /** Structured log entries produced during scraping. */
  logs?: JobLogEntry[] | null;
  /** Discovered and visited URL state. */
  urls?: JobUrlState | null;
  /** Terminal error message when status='failed'. */
  error_message?: string | null;
  started_at?: string | null;
  last_heartbeat_at?: string | null;
  cancel_requested_at?: string | null;
  completed_at?: string | null;
  created_at: string;
  updated_at?: string | null;
}
