/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * URL discovery state for a scrape job.
 */
export interface JobUrlState {
  /** All discovered listing URLs. */
  discovered?: string[];
  /** URLs successfully fetched. */
  visited?: string[];
  /** URLs that failed to fetch. */
  failed?: string[];
}
