/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

export type ListingTranslationResponseLocalesCachedItem =
  (typeof ListingTranslationResponseLocalesCachedItem)[keyof typeof ListingTranslationResponseLocalesCachedItem];

export const ListingTranslationResponseLocalesCachedItem = {
  en: 'en',
  pt: 'pt',
  es: 'es',
  fr: 'fr',
  de: 'de',
} as const;
