/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Lightweight listing representation for the selector UI.

Extends the base list fields with ``thumbnail_url`` (first media asset at
position=0) and ``is_enriched`` (True when any AI-enriched field is present).
 */
export interface ListingSearchItem {
  id: string;
  /** Slug identifying the data source partner. */
  source_partner: string;
  title?: string | null;
  property_type?: string | null;
  /** Portuguese typology code (e.g. 'T2'). */
  typology?: string | null;
  bedrooms?: number | null;
  /** Useful area in m². */
  area_useful_m2?: number | null;
  district?: string | null;
  county?: string | null;
  listing_type?: 'sale' | 'rent' | null;
  price_amount?: string | null;
  /** ISO 4217 currency code. */
  price_currency?: string | null;
  /** URL of the first media asset (position=0), if available. */
  thumbnail_url?: string | null;
  /** True when enriched_translations contains at least one locale. */
  is_enriched?: boolean;
}
