/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { ListingCreateEnrichedTranslations } from './listingCreateEnrichedTranslations';
import type { ListingCreateRawPayload } from './listingCreateRawPayload';
import type { MediaAssetCreate } from './mediaAssetCreate';

/**
 * Schema for creating a new listing (scraper → API).
 */
export interface ListingCreate {
  /** Listing transaction type. */
  listing_type?: 'sale' | 'rent' | null;
  /** Property type (e.g. 'apartment', 'house'). */
  property_type?: string | null;
  /** Portuguese typology code (e.g. 'T2', 'T3+1'). */
  typology?: string | null;
  /** Listing headline. */
  title?: string | null;
  bedrooms?: number | null;
  bathrooms?: number | null;
  /** Floor label (e.g. '3', 'R/C', 'último'). */
  floor?: string | null;
  /** Year of construction. */
  construction_year?: number | null;
  /** Energy certificate rating (e.g. A+, A, B, C, Isento). */
  energy_certificate?: string | null;
  price_amount?: number | string | null;
  /** ISO 4217 currency code. */
  price_currency?: string | null;
  price_per_m2?: number | string | null;
  /** Useful / habitable area in m². */
  area_useful_m2?: number | null;
  /** Gross area in m². */
  area_gross_m2?: number | null;
  /** Land / plot area in m². */
  area_land_m2?: number | null;
  district?: string | null;
  county?: string | null;
  parish?: string | null;
  full_address?: string | null;
  /** WGS-84 latitude. */
  latitude?: number | null;
  /** WGS-84 longitude. */
  longitude?: number | null;
  has_garage?: boolean | null;
  has_elevator?: boolean | null;
  has_balcony?: boolean | null;
  has_air_conditioning?: boolean | null;
  has_pool?: boolean | null;
  advertiser?: string | null;
  contacts?: string | null;
  /** Raw description as scraped (unprocessed). */
  raw_description?: string | null;
  /** Cleaned / normalised description. */
  description?: string | null;
  /** AI quality score (0–100). */
  description_quality_score?: number | null;
  /** SEO meta description (scraped). */
  meta_description?: string | null;
  /** AI-generated SEO content per locale: {"en": {title, description, meta_description}, "pt": {...}, ...} */
  enriched_translations?: ListingCreateEnrichedTranslations;
  /** Slug identifying the data source partner. */
  source_partner: string;
  /** Canonical URL of the listing on the partner site. */
  source_url?: string | null;
  /** Partner's own listing identifier. */
  partner_id?: string | null;
  /** Raw <title> of the scraped page. */
  page_title?: string | null;
  media_assets?: MediaAssetCreate[];
  /** Full raw partner payload, preserved for debugging. */
  raw_payload?: ListingCreateRawPayload;
}
