/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { ListListingsSortBy } from './listListingsSortBy';

export type ListListingsParams = {
  district?: string | null;
  county?: string | null;
  parish?: string | null;
  property_type?: string | null;
  typology?: string | null;
  listing_type?: string | null;
  source_partner?: string | null;
  scrape_job_id?: string | null;
  price_min?: number | string | null;
  price_max?: number | string | null;
  area_min?: number | null;
  area_max?: number | null;
  bedrooms_min?: number | null;
  bedrooms_max?: number | null;
  has_garage?: boolean | null;
  has_pool?: boolean | null;
  has_elevator?: boolean | null;
  created_after?: string | null;
  created_before?: string | null;
  search?: string | null;
  sort_by?: ListListingsSortBy;
  /**
   * @pattern ^(asc|desc)$
   */
  sort_order?: string;
  /**
   * @minimum 1
   */
  page?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  page_size?: number;
};
