/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * AI-generated SEO content per locale: {"en": {title, description, meta_description}, "pt": {...}, ...}
 */
export type ListingDetailReadEnrichedTranslations = { [key: string]: unknown } | null;
