/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { ListingStatsByDistrict } from './listingStatsByDistrict';
import type { ListingStatsByPropertyType } from './listingStatsByPropertyType';
import type { ListingStatsBySourcePartner } from './listingStatsBySourcePartner';
import type { ListingStatsByTypology } from './listingStatsByTypology';

/**
 * Aggregated listing statistics.
 */
export interface ListingStats {
  /** @minimum 0 */
  total_listings?: number;
  avg_price?: number | null;
  min_price?: number | null;
  max_price?: number | null;
  avg_area?: number | null;
  by_district?: ListingStatsByDistrict;
  by_property_type?: ListingStatsByPropertyType;
  by_source_partner?: ListingStatsBySourcePartner;
  by_typology?: ListingStatsByTypology;
}
