/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schema for partial listing updates (PATCH).

Intentionally omits scraper-internal fields (``page_title``,
``raw_description``) to prevent accidental overwrites via the API.
Only supplied fields are applied.
 */
export interface ListingUpdate {
  listing_type?: 'sale' | 'rent' | null;
  property_type?: string | null;
  typology?: string | null;
  title?: string | null;
  bedrooms?: number | null;
  bathrooms?: number | null;
  floor?: string | null;
  construction_year?: number | null;
  energy_certificate?: string | null;
  price_amount?: number | string | null;
  price_currency?: string | null;
  price_per_m2?: number | string | null;
  area_useful_m2?: number | null;
  area_gross_m2?: number | null;
  area_land_m2?: number | null;
  district?: string | null;
  county?: string | null;
  parish?: string | null;
  full_address?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  has_garage?: boolean | null;
  has_elevator?: boolean | null;
  has_balcony?: boolean | null;
  has_air_conditioning?: boolean | null;
  has_pool?: boolean | null;
  advertiser?: string | null;
  contacts?: string | null;
  description?: string | null;
  enriched_title?: string | null;
  enriched_description?: string | null;
  enriched_meta_description?: string | null;
  description_quality_score?: number | null;
  meta_description?: string | null;
}
