/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { ListingTranslationResponseLocalesCachedItem } from './listingTranslationResponseLocalesCachedItem';
import type { ListingTranslationResponseLocalesGeneratedItem } from './listingTranslationResponseLocalesGeneratedItem';
import type { ListingTranslationResponseResults } from './listingTranslationResponseResults';

/**
 * Response for the multi-locale translation enrichment endpoint.
 */
export interface ListingTranslationResponse {
  listing_id: string;
  /** True when results were persisted to the database. */
  applied?: boolean;
  /** Identifier of the AI model used. */
  model_used: string;
  keywords_used?: string[];
  /** Locales for which new content was generated (not reused from cache). */
  locales_generated?: ListingTranslationResponseLocalesGeneratedItem[];
  /** Locales reused from existing stored translations (force=False). */
  locales_cached?: ListingTranslationResponseLocalesCachedItem[];
  /** Full output keyed by locale code. */
  results?: ListingTranslationResponseResults;
}
