/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { ListingTranslationRequestLocalesItem } from './listingTranslationRequestLocalesItem';
import type { ListingTranslationRequestTranslationValues } from './listingTranslationRequestTranslationValues';

/**
 * Request to generate multi-locale SEO content from original scraped data.
 */
export interface ListingTranslationRequest {
  /** ID of the listing to translate/enrich. */
  listing_id: string;
  /** Target locales. Defaults to all supported: pt, es, fr, de. */
  locales?: ListingTranslationRequestLocalesItem[];
  /** Custom SEO keywords. If empty, keywords are inferred from the listing. */
  keywords?: string[];
  /** When True, regenerates locales that already have stored translations. */
  force?: boolean;
  /** When True, persists translation_values to the database. AI is never called in this mode — translation_values must be supplied. */
  apply?: boolean;
  /** Pre-computed locale outputs to persist. Required when apply=True. Keys must be valid SupportedLocale codes. */
  translation_values?: ListingTranslationRequestTranslationValues;
}
