/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

export type ListListingsSortBy = (typeof ListListingsSortBy)[keyof typeof ListListingsSortBy];

export const ListListingsSortBy = {
  price: 'price',
  area: 'area',
  bedrooms: 'bedrooms',
  created_at: 'created_at',
  updated_at: 'updated_at',
  district: 'district',
  title: 'title',
} as const;
