/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Compact listing schema for paginated list views.
 */
export interface ListingListRead {
  id: string;
  title?: string | null;
  source_partner: string;
  listing_type?: 'sale' | 'rent' | null;
  property_type?: string | null;
  typology?: string | null;
  price_amount?: string | null;
  price_currency?: string | null;
  price_per_m2?: string | null;
  district?: string | null;
  county?: string | null;
  area_useful_m2?: number | null;
  bedrooms?: number | null;
  bathrooms?: number | null;
  source_url?: string | null;
  created_at: string;
  updated_at: string;
}
