/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { LocaleEnrichmentOutput } from './localeEnrichmentOutput';

/**
 * Pre-computed locale outputs to persist. Required when apply=True. Keys must be valid SupportedLocale codes.
 */
export type ListingTranslationRequestTranslationValues = {
  [key: string]: LocaleEnrichmentOutput;
} | null;
