/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { LocaleEnrichmentOutput } from './localeEnrichmentOutput';

/**
 * Full output keyed by locale code.
 */
export type ListingTranslationResponseResults = { [key: string]: LocaleEnrichmentOutput };
