/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { ListingSearchItem } from './listingSearchItem';

/**
 * Search results for the listing selector.

Pagination metadata (page, page_size, total, pages) is carried by
``ApiResponse.meta``.
 */
export interface ListingSearchResponse {
  items?: ListingSearchItem[];
}
