/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { MediaAssetRead } from './mediaAssetRead';
import type { PriceHistoryRead } from './priceHistoryRead';

/**
 * Public listing detail response without internal raw scraped text.
 */
export interface ListingDetailRead {
  id: string;
  partner_id?: string | null;
  source_partner: string;
  source_url?: string | null;
  scrape_job_id?: string | null;
  listing_type?: 'sale' | 'rent' | null;
  property_type?: string | null;
  typology?: string | null;
  title?: string | null;
  bedrooms?: number | null;
  bathrooms?: number | null;
  floor?: string | null;
  construction_year?: number | null;
  energy_certificate?: string | null;
  price_amount?: string | null;
  price_currency?: string | null;
  price_per_m2?: string | null;
  area_useful_m2?: number | null;
  area_gross_m2?: number | null;
  area_land_m2?: number | null;
  district?: string | null;
  county?: string | null;
  parish?: string | null;
  full_address?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  has_garage?: boolean | null;
  has_elevator?: boolean | null;
  has_balcony?: boolean | null;
  has_air_conditioning?: boolean | null;
  has_pool?: boolean | null;
  advertiser?: string | null;
  contacts?: string | null;
  description?: string | null;
  description_quality_score?: number | null;
  meta_description?: string | null;
  created_at: string;
  updated_at: string;
  media_assets?: MediaAssetRead[];
  price_history?: PriceHistoryRead[];
}
