/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * AI-generated SEO content for a single locale.
 */
export interface LocaleEnrichmentOutput {
  /** Optimised listing title. */
  title?: string | null;
  /** Enriched listing description. */
  description?: string | null;
  /** SEO meta description (≤160 chars recommended). */
  meta_description?: string | null;
}
