/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Media asset payload for listing creation.
 */
export interface MediaAssetCreate {
  /** Absolute URL to the media asset. */
  url: string;
  /** Accessibility alt text. */
  alt_text?: string | null;
  /** Asset type: photo, floorplan, or video. */
  type?: 'photo' | 'floorplan' | 'video' | null;
  /** Display order (0-indexed). */
  position?: number | null;
}
