/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Media asset as returned by the API.
 */
export interface MediaAssetRead {
  id: string;
  url: string;
  alt_text?: string | null;
  type?: 'photo' | 'floorplan' | 'video' | null;
  position?: number | null;
}
