/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Pagination metadata attached to list responses.
 */
export interface Meta {
  /** Current page number (1-indexed). */
  page?: number | null;
  /** Number of items per page. */
  page_size?: number | null;
  /** Total number of items across all pages. */
  total?: number | null;
  /** Total number of pages. */
  pages?: number | null;
}
