/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { ListingListRead } from './listingListRead';

/**
 * Paginated listing items wrapper.

Pagination metadata (page, page_size, total, pages) is carried by
``ApiResponse.meta`` so the frontend reads it from a single, consistent
location regardless of which endpoint it calls.
 */
export interface PaginatedResponse {
  items?: ListingListRead[];
}
