/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { SiteIdentity } from './siteIdentity';

/**
 * Estatísticas agregadas de um partner, com o site associado embutido.
 */
export interface PartnerStats {
  /** Site config associado a este partner (join por site.key = source_partner). */
  site: SiteIdentity;
  /**
   * Total de imóveis actualmente na DB.
   * @minimum 0
   */
  total_listings?: number;
  /**
   * Imóveis actualizados nos últimos 7 dias.
   * @minimum 0
   */
  listings_updated_last_7_days?: number;
  avg_price?: string | null;
  min_price?: string | null;
  max_price?: string | null;
  /**
   * Imóveis com enriquecimento AI.
   * @minimum 0
   */
  enriched_count?: number;
  /**
   * Imóveis exportados para Imodigi.
   * @minimum 0
   */
  exported_to_imodigi_count?: number;
  /** updated_at mais recente entre todos os imóveis deste partner. */
  last_listing_updated_at?: string | null;
  /** UUID do job de scraping mais recente. */
  last_job_id?: string | null;
  /** Status do job mais recente. */
  last_job_status?: string | null;
  /** created_at do job mais recente. */
  last_job_at?: string | null;
  /** Imóveis scraped no último job. */
  last_job_scraped_count?: number | null;
}
