/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { PartnerStats } from './partnerStats';

/**
 * Resposta para GET /api/v1/dashboard/partners.
 */
export interface PartnerStatsResponse {
  partners?: PartnerStats[];
  /** @minimum 0 */
  total_partners?: number;
}
