/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Statistics row for a single source partner.
 */
export interface PartnerStats {
  /** Partner slug (e.g. 'pearls', 'habinedita'). */
  source_partner: string;
  /**
   * Total listings currently in the DB.
   * @minimum 0
   */
  total_listings?: number;
  /**
   * Listings updated in the past 7 days.
   * @minimum 0
   */
  listings_updated_last_7_days?: number;
  /** Average listing price. */
  avg_price?: number | null;
  /** Minimum listing price. */
  min_price?: number | null;
  /** Maximum listing price. */
  max_price?: number | null;
  /**
   * Listings with AI enrichment.
   * @minimum 0
   */
  enriched_count?: number;
  /**
   * Listings successfully exported to Imodigi.
   * @minimum 0
   */
  exported_to_imodigi_count?: number;
  /** Most recent updated_at across all listings of this partner. */
  last_listing_updated_at?: string | null;
  /** UUID of the most recent scrape job. */
  last_job_id?: string | null;
  /** Status of the most recent scrape job. */
  last_job_status?: string | null;
  /** created_at of the most recent scrape job. */
  last_job_at?: string | null;
  /** Listings scraped in the last job. */
  last_job_scraped_count?: number | null;
}
