/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * A single price history entry.
 */
export interface PriceHistoryRead {
  id: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  price_amount: string;
  /**
   * ISO 4217 currency code.
   * @minLength 3
   * @maxLength 3
   */
  price_currency: string;
  recorded_at: string;
}
