/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { SelectorValidateRequestSelectors } from './selectorValidateRequestSelectors';

/**
 * Request payload for selector validation.
 */
export interface SelectorValidateRequest {
  /** Mapping of field name → CSS selector to validate. */
  selectors: SelectorValidateRequestSelectors;
  /** URL to validate against. Defaults to the site's base_url when called via /{key}/validate-selectors. */
  url?: string | null;
}
