/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { SelectorValidationResult } from './selectorValidationResult';

/**
 * Validation report for a set of CSS selectors run against a live URL.
 */
export interface SelectorValidationReport {
  url: string;
  /** False if the page fetch failed or any selector has invalid CSS. */
  success: boolean;
  results: SelectorValidationResult[];
  /** Valid CSS selectors that matched 0 elements. */
  warnings?: string[];
  /** Selectors with invalid CSS syntax or a failed page fetch. */
  errors?: string[];
}
