/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Validation result for a single CSS selector.
 */
export interface SelectorValidationResult {
  field: string;
  selector: string;
  valid_css: boolean;
  /** @minimum 0 */
  matches: number;
  sample?: string | null;
}
