/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * A ranked selector candidate for a target field.
 */
export interface SelectorCandidate {
  selector: string;
  sample: string;
  /**
   * @minimum 0
   * @maximum 1
   */
  score: number;
}
