/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

export type SelectorListingsParams = {
  q?: string | null;
  source_partner?: string | null;
  is_enriched?: boolean | null;
  /**
   * @minimum 1
   */
  page?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  page_size?: number;
};
