/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Mapping of field name → CSS selector to validate.
 */
export type SelectorValidateRequestSelectors = { [key: string]: string };
