/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Extraction strategy: 'direct' applies CSS selectors to named fields; 'section' parses name/value pairs from structured sections.
 */
export type SiteConfigReadExtractionMode =
  (typeof SiteConfigReadExtractionMode)[keyof typeof SiteConfigReadExtractionMode];

export const SiteConfigReadExtractionMode = {
  section: 'section',
  direct: 'direct',
} as const;
