/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * CSS selectors used for parsing. Expected keys: listing_link, title, price, description, images, next_page.
 */
export type SiteConfigReadSelectors = { [key: string]: unknown };
