/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

export type SiteConfigSuggestResponseSource =
  (typeof SiteConfigSuggestResponseSource)[keyof typeof SiteConfigSuggestResponseSource];

export const SiteConfigSuggestResponseSource = {
  'json-ld': 'json-ld',
  heuristic: 'heuristic',
} as const;
