/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schedule status for a site — DB fields + live next_run_at from the in-memory scheduler.
 */
export interface SiteConfigScheduleInfo {
  site_key: string;
  schedule_enabled: boolean;
  schedule_interval_minutes: number | null;
  schedule_start_at: string | null;
  schedule_timezone: string;
  schedule_start_url: string | null;
  schedule_max_pages: number | null;
  /** Next scheduled run (None if scheduling is disabled or not yet registered). */
  next_run_at?: string | null;
}
