/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { SiteConfigCreateExtractionMode } from './siteConfigCreateExtractionMode';
import type { SiteConfigCreatePaginationType } from './siteConfigCreatePaginationType';
import type { SiteConfigCreateSelectors } from './siteConfigCreateSelectors';

/**
 * Schema for creating a new site configuration.
 */
export interface SiteConfigCreate {
  /**
   * Human-readable site name.
   * @minLength 1
   */
  name: string;
  /** Base URL of the target site (e.g. 'https://example.com'). */
  base_url: string;
  /** CSS selectors used for parsing. Expected keys: listing_link, title, price, description, images, next_page. */
  selectors?: SiteConfigCreateSelectors;
  /** Extraction strategy: 'direct' applies CSS selectors to named fields; 'section' parses name/value pairs from structured sections. */
  extraction_mode?: SiteConfigCreateExtractionMode;
  /** Pagination strategy used to move across result pages. */
  pagination_type?: SiteConfigCreatePaginationType;
  /** Query parameter name used when pagination_type='query_param' (for example 'page'). */
  pagination_param?: string | null;
  /** Regex pattern to filter listing URLs on listing pages. */
  link_pattern?: string | null;
  /** Regex to require image URLs to match (include-only filter). */
  image_filter?: string | null;
  /** Regex pattern — images whose URL matches are excluded (e.g. banners, logos). */
  image_exclude_filter?: string | null;
  /** Use a headless browser (Playwright) to render JavaScript before parsing. */
  use_js_render?: boolean;
  /** Whether this site config is enabled for scraping. */
  is_active?: boolean;
  /** Whether scheduled scraping is active for this site. */
  schedule_enabled?: boolean;
  /** Interval in minutes between scheduled runs. */
  schedule_interval_minutes?: number | null;
  /** When the first run should occur (None = start immediately). */
  schedule_start_at?: string | null;
  /** IANA timezone string for the schedule (e.g. 'Europe/Lisbon', 'UTC'). */
  schedule_timezone?: string;
  /** URL to begin scraping on scheduled runs (None = falls back to base_url). */
  schedule_start_url?: string | null;
  /** Max pages per scheduled run (None = uses server default). */
  schedule_max_pages?: number | null;
  /**
   * Unique site identifier slug (lowercase alphanumeric, hyphens and underscores allowed).
   * @minLength 2
   * @maxLength 50
   * @pattern ^[a-z0-9][a-z0-9_-]*$
   */
  key: string;
}
