/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { SiteConfigSuggestResponseCandidates } from './siteConfigSuggestResponseCandidates';
import type { SiteConfigSuggestResponseSource } from './siteConfigSuggestResponseSource';

/**
 * Suggested selectors grouped by target field.
 */
export interface SiteConfigSuggestResponse {
  source: SiteConfigSuggestResponseSource;
  candidates: SiteConfigSuggestResponseCandidates;
}
