/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { SiteConfigUpdateSelectors } from './siteConfigUpdateSelectors';

/**
 * Schema for partial site configuration updates (PATCH).

All fields are optional; only supplied fields are applied.
 */
export interface SiteConfigUpdate {
  name?: string | null;
  base_url?: string | null;
  selectors?: SiteConfigUpdateSelectors;
  extraction_mode?: 'section' | 'direct' | null;
  pagination_type?: 'html_next' | 'query_param' | 'incremental_path' | null;
  pagination_param?: string | null;
  link_pattern?: string | null;
  image_filter?: string | null;
  is_active?: boolean | null;
}
