/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Request payload for selector live preview.
 */
export interface SiteConfigPreviewRequest {
  /** @minLength 1 */
  url: string;
  selector: string;
}
