/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Subset leve de SiteConfigRead para uso em respostas de outros domínios.

Expõe apenas campos de identidade e estado — evita vazar
selectors, schedules e confidence scores fora do contexto /sites/*.
 */
export interface SiteIdentity {
  id: string;
  key: string;
  name: string;
  is_active: boolean;
  base_url: string;
}
