/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Pagination strategy used to move across result pages.
 */
export type SiteConfigCreatePaginationType =
  (typeof SiteConfigCreatePaginationType)[keyof typeof SiteConfigCreatePaginationType];

export const SiteConfigCreatePaginationType = {
  html_next: 'html_next',
  query_param: 'query_param',
  incremental_path: 'incremental_path',
  sitemap: 'sitemap',
} as const;
