/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { SiteConfigUpdateConfidenceScores } from './siteConfigUpdateConfidenceScores';
import type { SiteConfigUpdateSelectors } from './siteConfigUpdateSelectors';

/**
 * Schema for partial site configuration updates (PATCH).

All fields are optional; only supplied fields are applied.
 */
export interface SiteConfigUpdate {
  name?: string | null;
  base_url?: string | null;
  selectors?: SiteConfigUpdateSelectors;
  extraction_mode?: 'section' | 'direct' | null;
  pagination_type?: 'html_next' | 'query_param' | 'incremental_path' | 'sitemap' | null;
  pagination_param?: string | null;
  link_pattern?: string | null;
  image_filter?: string | null;
  image_exclude_filter?: string | null;
  use_js_render?: boolean | null;
  is_active?: boolean | null;
  /** Per-field confidence scores (0.0–1.0). */
  confidence_scores?: SiteConfigUpdateConfidenceScores;
  schedule_enabled?: boolean | null;
  schedule_interval_minutes?: number | null;
  schedule_start_at?: string | null;
  schedule_timezone?: string | null;
  schedule_start_url?: string | null;
  schedule_max_pages?: number | null;
}
