/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Per-field confidence scores (0.0–1.0).
 */
export type SiteConfigUpdateConfidenceScores = { [key: string]: number } | null;
