/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { SiteConfigCreateExtractionMode } from './siteConfigCreateExtractionMode';
import type { SiteConfigCreatePaginationType } from './siteConfigCreatePaginationType';
import type { SiteConfigCreateSelectors } from './siteConfigCreateSelectors';

/**
 * Schema for creating a new site configuration.
 */
export interface SiteConfigCreate {
  /**
   * Human-readable site name.
   * @minLength 1
   */
  name: string;
  /** Base URL of the target site (e.g. 'https://example.com'). */
  base_url: string;
  /** CSS selectors used for parsing. Expected keys: listing_link, title, price, description, images, next_page. */
  selectors?: SiteConfigCreateSelectors;
  /** Extraction strategy: 'direct' applies CSS selectors to named fields; 'section' parses name/value pairs from structured sections. */
  extraction_mode?: SiteConfigCreateExtractionMode;
  /** Pagination strategy used to move across result pages. */
  pagination_type?: SiteConfigCreatePaginationType;
  /** Query parameter name used when pagination_type='query_param' (for example 'page'). */
  pagination_param?: string | null;
  /** Regex pattern to filter listing URLs on listing pages. */
  link_pattern?: string | null;
  /** Regex pattern to filter image URLs (e.g. exclude thumbnails). */
  image_filter?: string | null;
  /** Whether this site config is enabled for scraping. */
  is_active?: boolean;
  /**
   * Unique site identifier slug (lowercase alphanumeric, hyphens and underscores allowed).
   * @minLength 2
   * @maxLength 50
   * @pattern ^[a-z0-9][a-z0-9_-]*$
   */
  key: string;
}
