/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { SelectorCandidate } from './selectorCandidate';

export type SiteConfigSuggestResponseCandidates = { [key: string]: SelectorCandidate[] };
