/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { SiteConfigReadConfidenceScores } from './siteConfigReadConfidenceScores';
import type { SiteConfigReadExtractionMode } from './siteConfigReadExtractionMode';
import type { SiteConfigReadPaginationType } from './siteConfigReadPaginationType';
import type { SiteConfigReadSelectors } from './siteConfigReadSelectors';

/**
 * Full site configuration response.
 */
export interface SiteConfigRead {
  /**
   * Human-readable site name.
   * @minLength 1
   */
  name: string;
  /** Base URL of the target site (e.g. 'https://example.com'). */
  base_url: string;
  /** CSS selectors used for parsing. Expected keys: listing_link, title, price, description, images, next_page. */
  selectors?: SiteConfigReadSelectors;
  /** Extraction strategy: 'direct' applies CSS selectors to named fields; 'section' parses name/value pairs from structured sections. */
  extraction_mode?: SiteConfigReadExtractionMode;
  /** Pagination strategy used to move across result pages. */
  pagination_type?: SiteConfigReadPaginationType;
  /** Query parameter name used when pagination_type='query_param' (for example 'page'). */
  pagination_param?: string | null;
  /** Regex pattern to filter listing URLs on listing pages. */
  link_pattern?: string | null;
  /** Regex to require image URLs to match (include-only filter). */
  image_filter?: string | null;
  /** Regex pattern — images whose URL matches are excluded (e.g. banners, logos). */
  image_exclude_filter?: string | null;
  /** Whether this site config is enabled for scraping. */
  is_active?: boolean;
  id: string;
  key: string;
  confidence_scores?: SiteConfigReadConfidenceScores;
  created_at: string;
  updated_at: string;
}
