/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Overall system health status.
 */
export type SystemHealthStatus = (typeof SystemHealthStatus)[keyof typeof SystemHealthStatus];

export const SystemHealthStatus = {
  healthy: 'healthy',
  unhealthy: 'unhealthy',
} as const;
