/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { SystemHealthDatabase } from './systemHealthDatabase';
import type { SystemHealthStatus } from './systemHealthStatus';

/**
 * Response schema for GET /health.
 */
export interface SystemHealth {
  /** Overall system health status. */
  status: SystemHealthStatus;
  /** Application version string. */
  version: string;
  /** Database connectivity status. */
  database?: SystemHealthDatabase;
}
