/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Database connectivity status.
 */
export type SystemHealthDatabase = (typeof SystemHealthDatabase)[keyof typeof SystemHealthDatabase];

export const SystemHealthDatabase = {
  ok: 'ok',
  degraded: 'degraded',
  unreachable: 'unreachable',
} as const;
