/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Normalized fields extracted from the listing page.
 */
export interface TestScrapeNormalized {
  title?: string | null;
  listing_type?: string | null;
  property_type?: string | null;
  typology?: string | null;
  bedrooms?: number | null;
  bathrooms?: number | null;
  price_amount?: number | null;
  price_currency?: string | null;
  price_per_m2?: number | null;
  area_useful_m2?: number | null;
  area_gross_m2?: number | null;
  area_land_m2?: number | null;
  district?: string | null;
  county?: string | null;
  parish?: string | null;
  energy_certificate?: string | null;
  construction_year?: number | null;
  has_garage?: boolean | null;
  has_pool?: boolean | null;
  has_elevator?: boolean | null;
  image_count?: number;
}
