/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Result of a test run against a listing/search results page.
 */
export interface TestListingPageResponse {
  url: string;
  success: boolean;
  /**
   * Total hrefs extracted before applying link_pattern.
   * @minimum 0
   */
  links_found: number;
  /**
   * Links that matched link_pattern (or all links if no pattern).
   * @minimum 0
   */
  links_matched: number;
  /** Up to 5 matched listing URLs. */
  sample_matched?: string[];
  /** Up to 5 URLs rejected by link_pattern. */
  sample_rejected?: string[];
  /** Up to 5 thumbnail URLs from thumbnail_selector. */
  thumbnail_preview?: string[];
  /** Next page URL extracted via next_page_selector, if configured. */
  next_page_url?: string | null;
  error?: string | null;
}
