/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { TestScrapeNormalized } from './testScrapeNormalized';
import type { TestScrapeResponseRaw } from './testScrapeResponseRaw';

/**
 * Result of a test-scrape run against a single listing URL.
 */
export interface TestScrapeResponse {
  url: string;
  success: boolean;
  /** Raw values extracted by the parser before normalisation. */
  raw?: TestScrapeResponseRaw;
  normalized?: TestScrapeNormalized | null;
  /** Critical fields (title, price, property_type, district) absent in the raw output. */
  missing_critical?: string[];
  /** Set when the fetch or parse failed entirely. */
  error?: string | null;
}
