/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Request payload for test-scrape.
 */
export interface TestScrapeRequest {
  /**
   * URL of a single listing detail page to test against.
   * @minLength 1
   */
  url: string;
}
