/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Raw values extracted by the parser before normalisation.
 */
export type TestScrapeResponseRaw = { [key: string]: unknown };
