/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Request payload for testing a listing/search results page.
 */
export interface TestListingPageRequest {
  /**
   * URL of a listing/search results page.
   * @minLength 1
   */
  url: string;
  /** Regex to test against found links. Overrides the site's saved link_pattern when provided. */
  link_pattern?: string | null;
  /** CSS selector to extract thumbnail images from listing cards. Optional. */
  thumbnail_selector?: string | null;
}
