/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

export type TriggerImodigiSyncParams = {
  /**
   * @minimum 1
   * @maximum 500
   */
  limit?: number;
  /**
   * Imodigi store ID. Overrides IMODIGI_CLIENT_ID for this sync.
   */
  client_id?: number | null;
  /**
   * Only sync listings from this source partner.
   */
  source_partner?: string | null;
  /**
   * Only sync enriched listings (true) or non-enriched listings (false).
   */
  is_enriched?: boolean | null;
  /**
   * Re-exportar listings já exportados para o Imodigi.
   */
  force?: boolean;
};
