/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Estatísticas consolidadas para uma determinada semana.
 */
export interface WeeklyStats {
  /** Nome de exibição (ex: '04/05 - 11/05'). */
  label: string;
  /**
   * Volume acumulado até ao fim dessa semana.
   * @minimum 0
   */
  total_listings?: number;
  /**
   * Novos imóveis capturados nessa semana.
   * @minimum 0
   */
  listings_captured?: number;
}
