/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * MVP-Scraper
 * Real Estate Scraper Backend API — scrape, enrich, and serve property listings.
 * OpenAPI spec version: 1.0.0
 */
import type { WeeklyStats } from './weeklyStats';

/**
 * Corpo da resposta para GET /api/v1/dashboard/weekly-stats.
 */
export interface WeeklyStatsResponse {
  /** Histórico cronológico das últimas semanas. */
  history?: WeeklyStats[];
  /**
   * Total de semanas retornadas (normalmente 6).
   * @minimum 0
   */
  total_weeks?: number;
}
